### ISSUE TITLE
Frame Data Meter Appears During Replays

### ISSUE THREAD

**Issue by juicer5024** [agersant/gbvsr-frame-meter#10]
With the latest release, the frame data meter appears during replays with no way of removing it. This wasn't the case with the previous build. This makes it difficult to parse through my replays since a large portion of the lower screen is now covered. It's not the biggest deal in the grand scheme of things, but thought you should be aware!

**Comment by agersant** [comment]
Hello! This was a feature added in 1.1.0. You can hide the frame meter in training or replays by pressing F4.
