### ISSUE TITLE
Would it be possible to list the first frame that connects next to advantage above the bar?

### ISSUE THREAD

**Issue by Flupperich** [agersant/gbvsr-frame-meter#16]
Either always, or only when the ingame Frame Information is turned off which usually provides this info at a glance.

I primarily request this for convenience of not having to count how many pegs into actives a move hit, while having the native Frame Information hidden to get rid of the ugly red/blue/yellow coloring on character. It is not important or urgent at all.

**Comment by agersant** [comment]
Not planning on adding this, I don't think it's worth the screen real estate. I do appreciate the suggestion though!

IMO the number on the meter is sufficient to read this quickly. (count is intentionally omitted for very short startups where counting the pegs is trivial)
