### ISSUE TITLE
The new official release crashes my game

### ISSUE THREAD

**Issue by HeksevilleHero** [agersant/gbvsr-frame-meter#19]
Any attempt to launch with the new version either crashes the game, or claims the game is crashed while running just fine, but without the mod enabled.

[crash_2024_07_08_00_51_33.dmp](https://github.com/user-attachments/files/16121680/crash_2024_07_08_00_51_33.dmp)

**Comment by agersant** [comment]
Thanks for the report!

Could you try opening `UE4SS-settings.ini` (in the folder where you uncompressed the mod) and making the following adjustment:

Change the `bUseUObjectArrayCache = true` line into `bUseUObjectArrayCache = false`.

I will be shipping this change in the next release too (assuming it works).

**Comment by HeksevilleHero** [comment]
No such luck, unfortunately. I've tried updating drivers, reinstalling the game, setting my BIOS to default, running Windows Memory Diagnostic, and SFC. The only other issue I could consider is the fact I have an AMD CPU, or that my windows is somehow borked. Here's the crash log from the newest version
[crash_2024_07_08_08_10_04.dmp](https://github.com/user-attachments/files/16124632/crash_2024_07_08_08_10_04.dmp)

**Comment by agersant** [comment]
Thanks for the update! I don't think there's anything wrong with your setup, thanks for all the troubleshooting attempts.

This mod uses UE4SS (an Unreal modding toolkit) and it has known race conditions between itself and the game, which can lead to crashes during startup. I've ran into them too but extremely infrequently. Somehow it's happening all the time for you. It's surprising that this new release triggers it, as the startup code of the mod has not changed at all.

You could try alt-tabbing while the game boots up to mess with the timings but I understand that's not a very practical or reliable solution. In a future release (not immediately), I am planning on updating to a more recent version of UE4SS, which might also fix this.

**Comment by HeksevilleHero** [comment]
It might have been a windows or driver issue, I reinstalled Windows (deleted everything) and now it works without an issue after being reinstalled.

**Comment by agersant** [comment]
Bizarre from start to end but I'm glad it's working now!

**Comment by agersant** [comment]
@HeksevilleHero 
Following up on your Reddit comment, could you try this build which has latest UE4SS? https://github.com/agersant/gbvsr-frame-meter/actions/runs/9853181821/artifacts/1681062175

I'm cautiously optimistic, I saw a change in there that seemed related to what I gleaned from the crash dumps.

**Comment by HeksevilleHero** [comment]
My apologies for the delay, I've been busy with work and just got a day off. After testing the game, both with and without the Intel Graphics Frame Monitor and Analyzer installed, it seems to work without any issues! I even restarted my computer to be sure the fix would stick, and it works like a charm! I'm glad I was able to help, and I apricate you taking the time to fix this issue.

**Comment by agersant** [comment]
Thank you for all the testing, this fix is now in the latest release 🙏
