### ISSUE TITLE
Feature request: Game pause/framestep advance

### ISSUE THREAD

**Issue by Triplicats** [agersant/gbvsr-frame-meter#22]
If possible, this would make it much easier to capture specific move images and hitboxes. 
For reference, I am referring to something like [this feature](https://github.com/Fyren/strivehitboxes/commit/d33ab1ac02d8172d830343e16f20a4d225144043) in one of the Guilty Gear Strive hitbox viewers, though the hotkeys it uses are also F3/F4 and would need to be changed.

**Comment by agersant** [comment]
This is actually already implemented but only in dev builds as I wasn't sure it would be useful beyond debugging 😅. I'll turn it for release builds in the patch 1.50 release.

**Comment by agersant** [comment]
Shipped in mod version 1.13.0
