### ISSUE TITLE
When the type of frames reaches the exact end of the meter, no digit is displayed

### ISSUE THREAD

**Issue by sente-descin** [agersant/gbvsr-frame-meter#23]
Current Behavior:
When active frames from Nier's 6S+H (Misfortune) reaches the exact end of the frame meter, it does not display any digits at the end. When the opponent's recovery reaches the exact end of the frame meter, it does not display any digits at the end.

Expected Behavior:
When active frames from Nier's 6S+H (Misfortune) reaches the exact end of the frame meter, it should display the number of active frames (in this case 6) as it does at any other time. The same should apply to the opponent's recovery.

<img width="953" alt="frame_meter_digit_bug" src="https://github.com/user-attachments/assets/3e493e9e-149c-48ed-b5ff-643e8f65e49e">

**Comment by agersant** [comment]
Fixed in 3e96c873a05a3da3301385dd09da40bd0a3de9bd
