### ISSUE TITLE
Can you also add a hitbox overlay mode?

### ISSUE THREAD

**Issue by shun9092** [agersant/gbvsr-frame-meter#5]
Can you also add a hitbox overlay mode?

If it is added, I think it will be more useful for playing games.

There was one in the previous version of the game, but there isn't one in Rising

**Comment by agersant** [comment]
This is on my radar as something I would like to add, but I am prioritizing fixes to the actual meter first.

**Comment by shun9092** [comment]
Got it. I'll be looking forward to the hitbox overlay being updated. Thanks.

**Comment by agersant** [comment]
Done and released today 🥳
